server.port=0
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${random.uuid}

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_home_tech
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=shopping_cart
spring.jpa.open-in-view=false

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

management.endpoints.web.exposure.include=health,info

spring.cloud.openfeign.circuitbreaker.enabled=true

resilience4j.circuitbreaker.configs.default.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.configs.default.slidingWindowSize=5
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=3
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=20s
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=2

resilience4j.timelimiter.configs.default.timeoutDuration=2s