spring:
  application:
    name: aggregator
  main:
    web-application-type: none

aggregator:
  kafka:
    topics:
      sensors: telemetry.sensors.v1
      snapshots: telemetry.snapshots.v1
    consumer:
      bootstrap-servers: localhost:9092
      group-id: aggregator-group
      client-id: aggregator-consumer
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 10
    producer:
      bootstrap-servers: localhost:9092
      client-id: aggregator-producer

logging:
  level:
    ru.yandex.practicum.aggregator: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true