spring:
  application:
    name: aggregator
  config:
    import: "optional:configserver:"
  cloud:
    config:
      fail-fast: false
      discovery:
        enabled: true
        serviceId: config-server

aggregator:
  kafka:
    topics:
      sensors: ${AGGREGATOR_KAFKA_TOPIC_SENSORS:telemetry.sensors.v1}
      snapshots: ${AGGREGATOR_KAFKA_TOPIC_SNAPSHOTS:telemetry.snapshots.v1}
    consumer:
      bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      groupId: ${AGGREGATOR_KAFKA_CONSUMER_GROUP_ID:aggregator}
      clientId: ${AGGREGATOR_KAFKA_CONSUMER_CLIENT_ID:aggregator-consumer}
      autoOffsetReset: earliest
      maxPollRecords: 10
    producer:
      bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      clientId: ${AGGREGATOR_KAFKA_PRODUCER_CLIENT_ID:aggregator-producer}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/